---
title: Factory Town
timezone: America/Los_Angeles
collections:
  pages:
    title: Pages
    output: true
    permalink: "/:name"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/project/:slug"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: projects
  values:
    layout: project
    Sub-Title: 
    Featured-Image: 
site: Factory Town
footer: This is the footer text.
site-intro-text: "WE TELL POWERFUL\n</br>\nIMAGINATIVE STORIES\n</br>\nIN THE UNIVERSAL\n</br>\nLANGUAGE
  OF VISUAL\n</br>\nART.  WE TELL POWERFUL\n</br> \nIMAGINATIVE STORIES IN THE\n</br>\nUNIVERSAL
  LANGUAGE\n</br>\nOF VISUAL ART WE TELL \n</br>\nPOWERFUL IMAGINATIVE STORIES\n</br>\nIN
  THE UNIVERSAL\n</br>\nLANGUAGE OF VISUAL\n</br>\nART WE TELL \n</br> \nPOWERFUL
  IMAGINATIVE\n</br>\nSTORIES IN THE\n</br>\nUNIVERSAL LANGUAGE\n</br>\nOF VISUAL
  ART\n</br>\n"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-sitemap
paginate: 10
paginate_path: "/blog/page:num/"
grid_alignments:
- top
- center
- bottom
