---
title: Factory Town
timezone: America/Los_Angeles
collections:
  pages:
    title: Pages
    output: true
    permalink: "/:name"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/project/:slug"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: projects
  values:
    layout: project
    Sub-Title: 
    Featured-Image: 
site: Factory Town
footer: "STEALING IS MEAN  |  STAY IN SCHOOL  |  CALL YOUR MOM  |  KEEP YOUR PROMISES
  \n |  HI@FACTORY.TOWN"
site-intro-text: "WE TELL POWERFUL\n</br>\nIMAGINATIVE STORIES\n</br>\nIN THE UNIVERSAL\n</br>\nLANGUAGE
  OF VISUAL\n</br>\nART.  WE BELIEVE THAT\n</br> \nSTORIES ARE THE  \n</br>\nMOST
  IMPORTANT   \n</br>\nCURRENCY WE HAVE. \n</br>\nWE KNOW YOU HAVE \n</br>\nSOMETHING
  TO SAY\n</br>\nTHAT NOBODY HAS \n</br>\nHEARD BEFORE, AND\n</br>\nWE INTEND TO HELP\n</br>\nYOU
  SAY IT. WE TELL\n</br> \nPOWERFUL IMAGINATIVE\n</br>\nSTORIES IN THE\n</br>\nUNIVERSAL
  LANGUAGE\n</br>\nOF VISUAL ART\n</br>\n"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-sitemap
paginate: 10
paginate_path: "/blog/page:num/"
grid_alignments:
- top
- center
- bottom
