---
title: Factory Town - A Creative Studio
timezone: America/Los_Angeles
collections:
  pages:
    title: Pages
    output: true
    permalink: "/:name"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/project/:slug"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: projects
  values:
    layout: project
    Sub-Title: 
    Featured-Image: 
    Video-Teaser-File: 
site: Factory Town - Creative Storytelling - Commercial Artists
metadata-desciption: Factory Town is a creative agency using film, photography, and
  environmental design to transform how clients and audiences see one another.
metadata-keywords: Factory Town Studio, Factory Town Films, Factory Town Creative,
  Factory Town Marketing, videography, filmmaking, creative storytellers,  Spokane,  filmmaking,
  pacific northwest, pnw, spokane filmmakers, creative filmmaker, creative illustration,
  photo illustration, environmental design
footer: "stealing is mean  |  stay in school  |  call your mom  | keep your promises
  \n |  hi@factorytown"
site-intro-text: 
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-sitemap
paginate: 10
paginate_path: "/blog/page:num/"
grid_alignments:
- top
- center
- bottom
