---
title: Factory Town - A Dual Director Studio
timezone: America/Los_Angeles
collections:
  pages:
    title: Pages
    output: true
    permalink: "/:name"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/project/:slug"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: projects
  values:
    layout: project
    Sub-Title:
    Featured-Image:
    Video-Teaser-File: 
site: Factory Town - A Dual Director Studio
footer: "stealing is mean  |  stay in school  |  call your mom  | keep your promises
  \n |  hi@factorytown"
site-intro-text: |-
  WE TELL POWERFUL
  </br>
  IMAGINATIVE STORIES
  </br>
  IN THE UNIVERSAL
  </br>
  LANGUAGE OF \
  </br>\
  VISUAL ART.
  </br>
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-sitemap
paginate: 10
paginate_path: "/blog/page:num/"
grid_alignments:
- top
- center
- bottom
