---
title: Factory Town
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
email: your-email@example.com
description: Description of Factory town.
baseurl: 
url: 
twitter_username: 
github_username: factorytown
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
