---
title: Factory Town
timezone: UTC
collections:
  film:
    title: Film
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: work
  values:
    Client: 
    Credits: 
    Teaser Image: 
    URL to Video: 
    Additional Images:
      Image: 
email: hello@factory.town
description: We are writer director duo.
baseurl: 
url: 
twitter_username: 
github_username: factorytown
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
